name: stat
dependencies:

-alabaster==0.7.12
-anaconda-client==1.7.2
-anaconda-navigator==1.9.6
-anaconda-project==0.8.2
-appnope==0.1.0
-appscript==1.0.1
-asn1crypto==0.24.0
-astroid==2.1.0
-astropy==3.1
-atomicwrites==1.2.1
-attrs==18.2.0
-Babel==2.6.0
-backcall==0.1.0
-backports.os==0.1.1
-backports.shutil-get-terminal-size==1.0.0
-beautifulsoup4==4.6.3
-bitarray==0.8.3
-bkcharts==0.2
-blaze==0.11.3
-bleach==3.0.2
-bokeh==1.0.2
-boto==2.49.0
-Bottleneck==1.2.1
-certifi==2018.11.29
-cffi==1.11.5
-chardet==3.0.4
-Click==7.0
-cloudpickle==0.6.1
-clyent==1.2.2
-colorama==0.4.1
-conda==4.5.12
-conda-build==3.17.6
-conda-verify==3.1.1
-contextlib2==0.5.5
-cryptography==2.4.2
-cycler==0.10.0
-Cython==0.29.2
-cytoolz==0.9.0.1
-dask==1.0.0
-datashape==0.5.4
-decorator==4.3.0
-defusedxml==0.5.0
-distributed==1.25.1
-docutils==0.14
-entrypoints==0.2.3
-et-xmlfile==1.0.1
-fastcache==1.0.2
-filelock==3.0.10
-Flask==1.0.2
-Flask-Cors==3.0.7
-future==0.17.1
-gevent==1.3.7
-glob2==0.6
-gmpy2==2.0.8
-greenlet==0.4.15
-h5py==2.8.0
-heapdict==1.0.0
-html5lib==1.0.1
-idna==2.8
-imageio==2.4.1
-imagesize==1.1.0
-importlib-metadata==0.6
-ipykernel==5.1.0
-ipython==7.2.0
-ipython-genutils==0.2.0
-ipywidgets==7.4.2
-isort==4.3.4
-itsdangerous==1.1.0
-jdcal==1.4
-jedi==0.13.2
-Jinja2==2.10
-jsonschema==2.6.0
-jupyter==1.0.0
-jupyter-client==5.2.4
-jupyter-console==6.0.0
-jupyter-core==4.4.0
-jupyterlab==0.35.3
-jupyterlab-server==0.2.0
-keyring==17.0.0
-kiwisolver==1.0.1
-matplotlib==3.0.2
-numpy==1.15.4
-pandas==0.23.4
-scikit-learn==0.20.1
-seaborn==0.9.0
